version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:15.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DATABASE}'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.4
    restart: always
    ports:
      - '8090:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
  # pg_eventserv:
  #   container_name: pg_eventserv
  #   image: pramsey/pg_eventserv:latest
  #   restart: always
  #   ports:
  #     - '8080:8080'
  #     - '7700:7700'
  #   environment:
  #     PGDATABASE: '${POSTGRES_DATABASE}'
  #     PGHOST: '${POSTGRES_HOST}'
  #     PGUSER: '${POSTGRES_USER}'
  #     PGPASSWORD: '${POSTGRES_PASSWORD}'
  #   depends_on:
  #     - postgres
volumes:
  postgres-data:
