version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: cimg/base:stable # Use a recent CircleCI convenience image
    steps:
      - checkout

      - setup_remote_docker: # Configure Docker for remote execution
          version: 20.10.17 # Specify a Docker version

      - run:
          name: Build Docker images
          command: docker-compose build

      - run:
          name: Deploy containers
          command: docker-compose up -d

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy
