---OPONENT JOINING
CREATE OR REPLACE FUNCTION NOTIFY_OPPONENT_JOINING() RETURNS trigger AS 
$BODY$ 
	BEGIN 
		IF NEW."state" = 'OPPONENT_JOINING' THEN 
			PERFORM pg_notify (
				NEW."roomID" || '##' || 'opponent_joining',
				row_to_json (NEW):: text
			);
		END IF;
		RETURN NULL;
	END;
$BODY$ LANGUAGE plpgsql VOLATILE COST 100;

CREATE OR REPLACE TRIGGER NOTIFY_OPPONENT_JOINING_TRIGGER AFTER UPDATE ON "Game" FOR EACH ROW EXECUTE PROCEDURE NOTIFY_OPPONENT_JOINING (); 
